[versions]
#jetbrains
kotlin = "1.9.0"
#AndroidX
androidx-print = "1.0.0"
#Simple tools
simple-commons = "de113ad025"
#Gradle
gradlePlugins-agp = "8.1.0"
#build
app-build-compileSDKVersion = "34"
app-build-targetSDK = "34"
app-build-minimumSDK = "23"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
#versioning
app-version-appId = "com.simplemobiletools.draw.pro"
app-version-versionCode = "80"
app-version-versionName = "6.9.4"
[libraries]
#AndroidX
androidx-print = { module = "androidx.print:print", version.ref = "androidx-print" }
#Simple Mobile Tools
simple-tools-commons = { module = "com.github.SimpleMobileTools:Simple-Commons", version.ref = "simple-commons" }
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
